export const GET_ALL_DATA_REQUESTED = 'GET_ALL_DATA_REQUESTED';
export const GET_ALL_DATA_SUCCEEDED = 'GET_ALL_DATA_SUCCEEDED';
export const GET_ALL_DATA_ERROR = 'GET_ALL_DATA_ERROR';

export const GET_PARTNERS_REQUESTED = 'GET_PARTNERS_REQUESTED';
export const GET_PARTNERS_SUCCEEDED = 'GET_PARTNERS_SUCCEEDED';
export const GET_PARTNERS_ERROR = 'GET_PARTNERS_ERROR';

export const GET_BUSINESSFORMS_REQUESTED = 'GET_BUSINESSFORMS_REQUESTED';
export const GET_BUSINESSFORMS_SUCCEEDED = 'GET_BUSINESSFORMS_SUCCEEDED';
export const GET_BUSINESSFORMS_ERROR = 'GET_BUSINESSFORMS_ERROR';

export const ADD_NEW_PARTNER_REQUESTED = 'ADD_NEW_PARTNER_REQUESTED';
export const ADD_NEW_PARTNER_SUCCEEDED = 'ADD_NEW_PARTNER_SUCCEEDED';
export const ADD_NEW_PARTNER_ERROR = 'ADD_NEW_PARTNER_ERROR';

export const DELETE_PARTNER_REQUESTED = 'DELETE_PARTNER_REQUESTED';
export const DELETE_PARTNER_SUCCEEDED = 'DELETE_PARTNER_SUCCEEDED';
export const DELETE_PARTNER_ERROR = 'DELETE_PARTNER_ERROR';
